In [12]:
import scipy
import numpy as np
import seaborn as sns
import fiona
import rasterio
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.utils.data as torch_data
import sys
from shapely import geometry
from rasterio.mask import mask
from tqdm import tqdm_notebook
from extractor_helper import extractor
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import xgboost as xgb
from catboost import CatBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score


In [13]:
import torch


In [14]:
torch.__version__

'1.4.0'

In [15]:
torch.cuda.current_device()

0

Data Import

In [16]:
sat_image = rasterio.open("project/1030010056130F00_MS_Pan_modified_KNN.tif")
sat_points1 = fiona.open("project/Points_MS_Pan_KNN.shp", "r")
sat_points2 = fiona.open("project/AB_points.shp", "r")

test2_img = rasterio.open("Eval/test2/pp_2_sat_modified.tif")
test2_points = fiona.open("Eval/test2/points_2_modified_Copy.shp", "r")

test3_img = rasterio.open("Eval/test3/pp_3_sat_modified.tif")
test3_points = fiona.open("Eval/test3/targets_Copy.shp", "r")

test4_img = rasterio.open("Eval/test4/pp_4_sat_modified_spline.tif")
test4_points = fiona.open("Eval/test4/modified_points_Copy.shp", "r")

In [17]:
class TreesData():
  def __init__(self, X, y):
    super().__init__()
    self.X = torch.tensor(X, dtype=torch.float32)
    self.y = torch.tensor(y, dtype=torch.float32)
    
  def __len__(self):
    return self.X.shape[0]
  
  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]
    

In [18]:
class AutoEncoder(nn.Module):
  def __init__(self,encoder,decoder):
    super().__init__()
    self.encoder = encoder
    self.decoder = decoder
    
  def forward(self,x):
    z = self.encoder(x)
    out = self.decoder(z)
    return out

In [19]:
def train(epochs, net, criterion, optimizer,
          train_loader, val_loader, scheduler=None,
          verbose=True, save_dir=None):
  loss_tr =0
  loss_val =0
  net.to(device)

  for epoch in range(1,epochs+1):
      net.train()
      for X,_ in train_loader:
          X = X.to(device)
          pred = net(X)
          loss = criterion(pred,X)
          optimizer.zero_grad()
          loss.backward()
          optimizer.step()
    
      net.eval()
      for X,_ in val_loader:
          X = X.to(device)
          val_pred = net(X)
          val_loss = criterion(val_pred,X)
#       loss /= len(train_loader)
#       val_loss /= len(val_loader)
      loss_tr +=loss.item()
      loss_val +=val_loss.item()

  
      if scheduler is not None:
          schduler.step()
    
      freq = max(epochs//20,1)
      if verbose and epoch%freq==0:
        print('Epoch {}/{} || Loss:  Train {:.6f} | Validation {:.6f}'.format(epoch, epochs, loss.item(), val_loss.item())) 
  return (loss_tr/epochs), (loss_val/epochs)

In [20]:
encoder = lambda hid,red_size: nn.Sequential(
  
  nn.Conv2d(8,60,3),
  nn.BatchNorm2d(60),
  nn.ReLU(),

  nn.Conv2d(60,200,3),
  nn.BatchNorm2d(200),
  nn.ReLU(),

  nn.Flatten(),
  nn.Linear(200*red_size*red_size,300),
  nn.BatchNorm1d(300),
  nn.ReLU(),

  nn.Linear(300,hid),
  nn.BatchNorm1d(hid),
)

decoder = lambda hid,orginal_size: nn.Sequential(
  nn.Linear(hid,600),
  nn.BatchNorm1d(600),
  nn.ReLU(),

  nn.Linear(600,1000),
  nn.BatchNorm1d(1000),
  nn.ReLU(),

  nn.Linear(1000,orginal_size*orginal_size*8),
  nn.Sigmoid(),
  Unflatten(),
)


In [21]:
class Unflatten(nn.Module):
  def forward(self, input):
    return input.reshape(input.shape[0],8,orginal_size,orginal_size)

In [22]:
import pandas as pd 

b = ['AdaBoostClassifier_acc_tr', 'AdaBoostClassifier_acc_ts','AdaBoostClassifier_f1_tr', 'AdaBoostClassifier_f1_ts','Ada_params',
     'XGBClassifier_acc_tr', 'XGBClassifier_acc_ts','XGBClassifier_f1_tr', 'XGBClassifier_f1_ts','XGB_params',
     'CatBoostClassifier_acc_tr', 'CatBoostClassifier_acc_ts','CatBoostClassifier_f1_tr', 'CatBoostClassifier_f1_ts','Cat_params',
     'RandomForestClassifier_acc_tr', 'RandomForestClassifier_acc_ts','RandomForestClassifier_f1_tr', 'RandomForestClassifier_f1_ts','RF_params',
     'SVC_acc_tr', 'SVC_acc_ts','SVC_f1_tr', 'SVC_f1_ts','SVC_params',
     'LogisticRegression_acc_tr', 'LogisticRegression_acc_ts','LogisticRegression_f1_tr', 'LogisticRegression_f1_ts','LG_params',
     'tr_loss','val_loss']

d = [0]*32


In [23]:
import sklearn
sklearn.__version__

'0.22.2.post1'

In [25]:
from tqdm import tqdm
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

for cut_size in tqdm((range(3,16,2))):
    results = pd.DataFrame(index=b,data=d)
    for bot_neck in tqdm((range(40,130,20))):

        patch2,coordinates2,labels2, = extractor(test2_img,test2_points,size=cut_size, normalize=True,labeling=True)
        patch3,coordinates3,labels3, = extractor(test3_img,test3_points,size=cut_size, normalize=True,labeling=True)
        patch4,coordinates4,labels4, = extractor(test4_img,test4_points,size=cut_size, normalize=True,labeling=True)

        patch2,patch3, patch4 = np.array(patch2), np.array(patch3), np.array(patch4)
        labels2, labels3, labels4 = np.array(labels2), np.array(labels3), np.array(labels4)
        patch2, patch3, patch4 = np.moveaxis(patch2,3,1), np.moveaxis(patch3,3,1), np.moveaxis(patch4,3,1)

        patch = np.concatenate((patch2, patch3, patch4),axis=0)
        patch = torch.tensor(patch, dtype=torch.float32).to(device)
        labels = np.concatenate((labels2,labels3,labels4),axis=0)

#         sm_images1, sm_points1,_ = extractor(sat_image,sat_points1,size=cut_size, normalize=True)
#         sm_images2,sm_point2,_= extractor(sat_image,sat_points2,size=cut_size, normalize=True)
#         data = np.array(sm_images1+sm_images2)
#         data = np.moveaxis(data,3,1)
#         targets = np.zeros(shape = data.shape[0])

#         X_Train, X_Test, Y_Train, Y_Test = train_test_split(data, targets,test_size=.20, shuffle=True,random_state=12)
#         train_data = TreesData(X_Train,Y_Train)
#         test_data = TreesData(X_Test,Y_Test)

#         orginal_size = X_Test.shape[-1]
#         side = lambda x: int(((x - 3)/1)+1)
#         red_size  = side(side(orginal_size))

#         del X_Train, X_Test,Y_Train,Y_Test,data,targets

#         net = AutoEncoder(encoder(bot_neck,red_size), decoder(bot_neck,orginal_size))
#         criterion = nn.MSELoss()
#         optimizer = torch.optim.Adam(net.parameters())
#         scheduler = None 
#         train_loader = torch_data.DataLoader(train_data,batch_size=300, shuffle=True)
#         val_loader = torch_data.DataLoader(test_data,batch_size=300,shuffle=True)
        
#         lsstr, lssts = train(200, net, criterion, optimizer, train_loader, val_loader,scheduler)
#         print(lsstr, lssts)

        net = torch.load(f'models/net_cutsize{cut_size}butneck{bot_neck}.pth')
        net.eval()
        embeddings_res = net.encoder(patch)
        embeddings_res = embeddings_res.cpu().detach().numpy()
        ros = SMOTE(random_state=12)
#         ros = RandomOverSampler(random_state=12)
        print(np.bincount(labels))
        x_train,x_test,y_train,y_test = train_test_split(embeddings_res,
                                                         labels,test_size=.2,
                                                         shuffle=True,
                                                         random_state=12,
                                                         stratify=labels)
       
        
        x_train, y_train = ros.fit_resample(x_train, y_train)
        print(np.bincount(y_train))
        

        clf1 = AdaBoostClassifier(n_estimators=100, random_state=12)
        clf2 = xgb.XGBClassifier(n_estimators=100, n_jobs=-1, random_state=12, ) 
        clf3 = CatBoostClassifier(iterations=1000, learning_rate=0.1,verbose=False)
        clf4 = RandomForestClassifier(n_jobs=-1, random_state=12)
        clf5 = SVC()
        clf6 = LogisticRegression(n_jobs=-1)

        parameters = [{"n_estimators":[20,30,50,100,150,200]},
                      {"n_estimators":[50,100,150,200,300,400,500], "max_depth":[3,5,6,10]},
                      {},
                      {"n_estimators":[50,100,150,200,300,400,500], "max_depth":[3,5,6,10,15,20]},
                      {'kernel':['rbf','poly','sigmoid'],'gamma':['scale','auto'],'decision_function_shape':['ovo', 'ovr']},
                      {}]

        clfs = {"Adaboost":clf1, "XGboost":clf2,'Catboost':clf3,"Random Forest":clf4, "SVM": clf5, "LogisticRegression": clf6}

        colm = []
        for i,names in enumerate(clfs):
              clf = GridSearchCV(clfs[names],param_grid=parameters[i], cv=5, n_jobs=-1, scoring='f1_macro',).fit(x_train,y_train)
              pred_train = clf.predict(x_train)
              pred_test = clf.predict(x_test)
              print(f'{names}: best params {clf.best_params_}\n')
              print('Train accuracy:\t {:.3}'.format(accuracy_score(y_train,pred_train)))
              print('Test accuracy:\t {:.3}'.format(accuracy_score(y_test,pred_test)))
              colm.append(accuracy_score(y_train,pred_train))
              colm.append(accuracy_score(y_test,pred_test))
              print('Train precision: {:.3}'.format(precision_score(y_train,pred_train,average='macro')))
              print('Test precision:\t {:.3}'.format(precision_score(y_test,pred_test,average='macro')))

              print('Train recall:\t {:.3}'.format(recall_score(y_train,pred_train,average='macro')))
              print('Test recall:\t {:.3}'.format(recall_score(y_test,pred_test,average='macro')))

              print('Train f1_score:\t {:.3}'.format(f1_score(y_train,pred_train,average='macro')))
              print('Test f1_score:\t {:.3}'.format(f1_score(y_test,pred_test,average='macro')),'\n',"-"*30)
              colm.append(f1_score(y_train,pred_train,average='macro'))
              colm.append(f1_score(y_test,pred_test,average='macro'))
              clfs[names]=clf
              colm.append(clf.best_params_)
        colm.append(0)
        colm.append(0)
        index = len(results.columns)
        results.insert(index,f'cut_size {cut_size}/bot_neck {bot_neck}',colm)
        results.to_csv(f'results{cut_size}.csv')




  0%|          | 0/7 [00:00<?, ?it/s]


  0%|          | 0/5 [00:00<?, ?it/s]

[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.78
Test accuracy:	 0.685
Train precision: 0.799
Test precision:	 0.575
Train recall:	 0.78
Test recall:	 0.567
Train f1_score:	 0.785
Test f1_score:	 0.57 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.714
Train precision: 0.999
Test precision:	 0.563
Train recall:	 0.999
Test recall:	 0.582
Train f1_score:	 0.999
Test f1_score:	 0.572 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.749
Train precision: 0.999
Test precision:	 0.574
Train recall:	 0.999
Test recall:	 0.591
Train f1_score:	 0.999
Test f1_score:	 0.582 
 ------------------------------
Random Forest: best params {'max_depth': 15, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.764
Train precision: 0.999
Test precision:	 0.584
Train recall:	 0.999
Test recall:	 0.598
Train 




 20%|██        | 1/5 [01:50<07:21, 110.35s/it]

LogisticRegression: best params {}

Train accuracy:	 0.807
Test accuracy:	 0.65
Train precision: 0.805
Test precision:	 0.583
Train recall:	 0.807
Test recall:	 0.678
Train f1_score:	 0.805
Test f1_score:	 0.593 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.748
Test accuracy:	 0.64
Train precision: 0.76
Test precision:	 0.57
Train recall:	 0.748
Test recall:	 0.578
Train f1_score:	 0.752
Test f1_score:	 0.564 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 150}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.579
Train recall:	 0.999
Test recall:	 0.596
Train f1_score:	 0.999
Test f1_score:	 0.586 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.719
Train precision: 0.999
Test precision:	 0.596
Train recall:	 0.999
Test recall:	 0.614
Train f1_score:	 0.999
Test f1_score:	 




 40%|████      | 2/5 [04:05<05:53, 117.93s/it]

LogisticRegression: best params {}

Train accuracy:	 0.847
Test accuracy:	 0.67
Train precision: 0.845
Test precision:	 0.611
Train recall:	 0.847
Test recall:	 0.726
Train f1_score:	 0.843
Test f1_score:	 0.614 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 50}

Train accuracy:	 0.687
Test accuracy:	 0.621
Train precision: 0.725
Test precision:	 0.514
Train recall:	 0.687
Test recall:	 0.48
Train f1_score:	 0.695
Test f1_score:	 0.495 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.7
Train precision: 0.999
Test precision:	 0.604
Train recall:	 0.999
Test recall:	 0.629
Train f1_score:	 0.999
Test f1_score:	 0.615 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.759
Train precision: 0.999
Test precision:	 0.629
Train recall:	 0.999
Test recall:	 0.634
Train f1_score:	 0.999
Test f1_score:	 0




 60%|██████    | 3/5 [06:45<04:20, 130.47s/it]

LogisticRegression: best params {}

Train accuracy:	 0.885
Test accuracy:	 0.695
Train precision: 0.884
Test precision:	 0.615
Train recall:	 0.885
Test recall:	 0.731
Train f1_score:	 0.883
Test f1_score:	 0.635 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.793
Test accuracy:	 0.68
Train precision: 0.818
Test precision:	 0.534
Train recall:	 0.793
Test recall:	 0.534
Train f1_score:	 0.799
Test f1_score:	 0.534 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 150}

Train accuracy:	 0.999
Test accuracy:	 0.685
Train precision: 0.999
Test precision:	 0.527
Train recall:	 0.999
Test recall:	 0.551
Train f1_score:	 0.999
Test f1_score:	 0.538 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.749
Train precision: 0.999
Test precision:	 0.589
Train recall:	 0.999
Test recall:	 0.594
Train f1_score:	 0.999
Test f1_score




 80%|████████  | 4/5 [09:59<02:29, 149.49s/it]

LogisticRegression: best params {}

Train accuracy:	 0.909
Test accuracy:	 0.626
Train precision: 0.908
Test precision:	 0.546
Train recall:	 0.909
Test recall:	 0.608
Train f1_score:	 0.908
Test f1_score:	 0.555 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 50}

Train accuracy:	 0.737
Test accuracy:	 0.65
Train precision: 0.759
Test precision:	 0.565
Train recall:	 0.737
Test recall:	 0.594
Train f1_score:	 0.743
Test f1_score:	 0.57 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 200}

Train accuracy:	 0.999
Test accuracy:	 0.764
Train precision: 0.999
Test precision:	 0.574
Train recall:	 0.999
Test recall:	 0.616
Train f1_score:	 0.999
Test f1_score:	 0.593 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.744
Train precision: 0.999
Test precision:	 0.571
Train recall:	 0.999
Test recall:	 0.595
Train f1_score:	 0.999
Test f1_score:	




100%|██████████| 5/5 [13:36<00:00, 163.32s/it]


 14%|█▍        | 1/7 [13:36<1:21:39, 816.59s/it]


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.907
Test accuracy:	 0.724
Train precision: 0.906
Test precision:	 0.615
Train recall:	 0.907
Test recall:	 0.69
Train f1_score:	 0.905
Test f1_score:	 0.632 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.763
Test accuracy:	 0.621
Train precision: 0.778
Test precision:	 0.537
Train recall:	 0.763
Test recall:	 0.511
Train f1_score:	 0.768
Test f1_score:	 0.522 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.596
Train recall:	 0.999
Test recall:	 0.598
Train f1_score:	 0.999
Test f1_score:	 0.596 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.704
Train precision: 0.999
Test precision:	 0.595
Train recall:	 0.999
Test recall:	 0.6
Train f1_score:	 0.999
Test f1_score:	




 20%|██        | 1/5 [01:47<07:10, 107.65s/it]

LogisticRegression: best params {}

Train accuracy:	 0.792
Test accuracy:	 0.645
Train precision: 0.789
Test precision:	 0.582
Train recall:	 0.792
Test recall:	 0.64
Train f1_score:	 0.789
Test f1_score:	 0.588 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.75
Test accuracy:	 0.631
Train precision: 0.76
Test precision:	 0.549
Train recall:	 0.75
Test recall:	 0.566
Train f1_score:	 0.753
Test f1_score:	 0.551 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.586
Train recall:	 0.999
Test recall:	 0.589
Train f1_score:	 0.999
Test f1_score:	 0.587 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.749
Train precision: 0.999
Test precision:	 0.646
Train recall:	 0.999
Test recall:	 0.617
Train f1_score:	 0.999
Test f1_score:	 




 40%|████      | 2/5 [04:01<05:46, 115.43s/it]

LogisticRegression: best params {}

Train accuracy:	 0.84
Test accuracy:	 0.64
Train precision: 0.837
Test precision:	 0.577
Train recall:	 0.84
Test recall:	 0.668
Train f1_score:	 0.837
Test f1_score:	 0.59 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.76
Test accuracy:	 0.626
Train precision: 0.776
Test precision:	 0.546
Train recall:	 0.76
Test recall:	 0.549
Train f1_score:	 0.764
Test f1_score:	 0.546 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 50}

Train accuracy:	 0.999
Test accuracy:	 0.729
Train precision: 0.999
Test precision:	 0.65
Train recall:	 0.999
Test recall:	 0.612
Train f1_score:	 0.999
Test f1_score:	 0.618 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.734
Train precision: 0.999
Test precision:	 0.688
Train recall:	 0.999
Test recall:	 0.609
Train f1_score:	 0.999
Test f1_score:	 0.6




 60%|██████    | 3/5 [06:43<04:18, 129.43s/it]

LogisticRegression: best params {}

Train accuracy:	 0.882
Test accuracy:	 0.591
Train precision: 0.88
Test precision:	 0.53
Train recall:	 0.882
Test recall:	 0.601
Train f1_score:	 0.88
Test f1_score:	 0.541 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.757
Test accuracy:	 0.635
Train precision: 0.777
Test precision:	 0.561
Train recall:	 0.757
Test recall:	 0.551
Train f1_score:	 0.763
Test f1_score:	 0.55 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 50}

Train accuracy:	 0.999
Test accuracy:	 0.729
Train precision: 0.999
Test precision:	 0.577
Train recall:	 0.999
Test recall:	 0.58
Train f1_score:	 0.999
Test f1_score:	 0.578 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.744
Train precision: 0.999
Test precision:	 0.566
Train recall:	 0.999
Test recall:	 0.595
Train f1_score:	 0.999
Test f1_score:	 0.

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest: best params {'max_depth': 20, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.719
Train precision: 0.999
Test precision:	 0.799
Train recall:	 0.999
Test recall:	 0.592
Train f1_score:	 0.999
Test f1_score:	 0.61 
 ------------------------------
SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.978
Test accuracy:	 0.754
Train precision: 0.978
Test precision:	 0.826
Train recall:	 0.978
Test recall:	 0.625
Train f1_score:	 0.978
Test f1_score:	 0.641 
 ------------------------------





 80%|████████  | 4/5 [09:51<02:27, 147.07s/it]

LogisticRegression: best params {}

Train accuracy:	 0.903
Test accuracy:	 0.64
Train precision: 0.902
Test precision:	 0.553
Train recall:	 0.903
Test recall:	 0.594
Train f1_score:	 0.901
Test f1_score:	 0.563 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.752
Test accuracy:	 0.66
Train precision: 0.767
Test precision:	 0.606
Train recall:	 0.752
Test recall:	 0.616
Train f1_score:	 0.757
Test f1_score:	 0.606 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.7
Train precision: 0.999
Test precision:	 0.583
Train recall:	 0.999
Test recall:	 0.586
Train f1_score:	 0.999
Test f1_score:	 0.584 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.739
Train precision: 0.999
Test precision:	 0.627
Train recall:	 0.999
Test recall:	 0.62
Train f1_score:	 0.999
Test f1_score:	 0




100%|██████████| 5/5 [13:33<00:00, 162.77s/it]


 29%|██▊       | 2/7 [27:10<1:07:58, 815.77s/it]


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.915
Test accuracy:	 0.606
Train precision: 0.914
Test precision:	 0.531
Train recall:	 0.915
Test recall:	 0.556
Train f1_score:	 0.914
Test f1_score:	 0.527 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.746
Test accuracy:	 0.596
Train precision: 0.76
Test precision:	 0.53
Train recall:	 0.746
Test recall:	 0.543
Train f1_score:	 0.75
Test f1_score:	 0.533 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.65
Train precision: 0.999
Test precision:	 0.515
Train recall:	 0.999
Test recall:	 0.515
Train f1_score:	 0.999
Test f1_score:	 0.515 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.724
Train precision: 0.999
Test precision:	 0.622
Train recall:	 0.999
Test recall:	 0.595
Train f1_score:	 0.999
Test f1_score:	 




 20%|██        | 1/5 [01:48<07:12, 108.03s/it]

LogisticRegression: best params {}

Train accuracy:	 0.741
Test accuracy:	 0.542
Train precision: 0.736
Test precision:	 0.501
Train recall:	 0.741
Test recall:	 0.586
Train f1_score:	 0.737
Test f1_score:	 0.498 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 100}

Train accuracy:	 0.754
Test accuracy:	 0.635
Train precision: 0.763
Test precision:	 0.543
Train recall:	 0.754
Test recall:	 0.543
Train f1_score:	 0.758
Test f1_score:	 0.541 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.69
Train precision: 0.999
Test precision:	 0.611
Train recall:	 0.999
Test recall:	 0.583
Train f1_score:	 0.999
Test f1_score:	 0.584 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.714
Train precision: 0.999
Test precision:	 0.668
Train recall:	 0.999
Test recall:	 0.597
Train f1_score:	 0.999
Test f1_score

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 40%|████      | 2/5 [04:01<05:47, 115.80s/it]

LogisticRegression: best params {}

Train accuracy:	 0.838
Test accuracy:	 0.616
Train precision: 0.835
Test precision:	 0.559
Train recall:	 0.838
Test recall:	 0.59
Train f1_score:	 0.836
Test f1_score:	 0.553 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.787
Test accuracy:	 0.621
Train precision: 0.796
Test precision:	 0.573
Train recall:	 0.787
Test recall:	 0.618
Train f1_score:	 0.789
Test f1_score:	 0.572 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 150}

Train accuracy:	 0.999
Test accuracy:	 0.69
Train precision: 0.999
Test precision:	 0.583
Train recall:	 0.999
Test recall:	 0.573
Train f1_score:	 0.999
Test f1_score:	 0.576 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.56
Train recall:	 0.999
Test recall:	 0.55
Train f1_score:	 0.999
Test f1_score:	 

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.986
Test accuracy:	 0.734
Train precision: 0.986
Test precision:	 0.567
Train recall:	 0.986
Test recall:	 0.582
Train f1_score:	 0.986
Test f1_score:	 0.574 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 60%|██████    | 3/5 [06:46<04:20, 130.29s/it]

LogisticRegression: best params {}

Train accuracy:	 0.858
Test accuracy:	 0.542
Train precision: 0.857
Test precision:	 0.503
Train recall:	 0.858
Test recall:	 0.542
Train f1_score:	 0.856
Test f1_score:	 0.5 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.725
Test accuracy:	 0.675
Train precision: 0.757
Test precision:	 0.57
Train recall:	 0.725
Test recall:	 0.552
Train f1_score:	 0.729
Test f1_score:	 0.559 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.623
Train recall:	 0.999
Test recall:	 0.594
Train f1_score:	 0.999
Test f1_score:	 0.603 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.729
Train precision: 0.999
Test precision:	 0.695
Train recall:	 0.999
Test recall:	 0.591
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 80%|████████  | 4/5 [10:04<02:30, 150.68s/it]

LogisticRegression: best params {}

Train accuracy:	 0.909
Test accuracy:	 0.591
Train precision: 0.907
Test precision:	 0.535
Train recall:	 0.909
Test recall:	 0.608
Train f1_score:	 0.907
Test f1_score:	 0.55 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.711
Test accuracy:	 0.586
Train precision: 0.727
Test precision:	 0.497
Train recall:	 0.711
Test recall:	 0.475
Train f1_score:	 0.715
Test f1_score:	 0.485 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 200}

Train accuracy:	 0.999
Test accuracy:	 0.68
Train precision: 0.999
Test precision:	 0.545
Train recall:	 0.999
Test recall:	 0.52
Train f1_score:	 0.999
Test f1_score:	 0.529 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.714
Train precision: 0.999
Test precision:	 0.554
Train recall:	 0.999
Test recall:	 0.574
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.987
Test accuracy:	 0.724
Train precision: 0.987
Test precision:	 0.561
Train recall:	 0.987
Test recall:	 0.579
Train f1_score:	 0.987
Test f1_score:	 0.57 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



100%|██████████| 5/5 [13:45<00:00, 165.08s/it]


 43%|████▎     | 3/7 [40:55<54:34, 818.66s/it]  


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.92
Test accuracy:	 0.64
Train precision: 0.919
Test precision:	 0.549
Train recall:	 0.92
Test recall:	 0.588
Train f1_score:	 0.92
Test f1_score:	 0.562 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.81
Test accuracy:	 0.557
Train precision: 0.819
Test precision:	 0.44
Train recall:	 0.81
Test recall:	 0.441
Train f1_score:	 0.813
Test f1_score:	 0.44 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 150}

Train accuracy:	 0.999
Test accuracy:	 0.64
Train precision: 0.999
Test precision:	 0.486
Train recall:	 0.999
Test recall:	 0.498
Train f1_score:	 0.999
Test f1_score:	 0.491 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.68
Train precision: 0.999
Test precision:	 0.523
Train recall:	 0.999
Test recall:	 0.532
Train f1_score:	 0.999
Test f1_score:	 0.526

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 20%|██        | 1/5 [01:40<06:40, 100.22s/it]

SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.979
Test accuracy:	 0.714
Train precision: 0.98
Test precision:	 0.573
Train recall:	 0.979
Test recall:	 0.543
Train f1_score:	 0.979
Test f1_score:	 0.554 
 ------------------------------
LogisticRegression: best params {}

Train accuracy:	 0.725
Test accuracy:	 0.532
Train precision: 0.719
Test precision:	 0.494
Train recall:	 0.725
Test recall:	 0.591
Train f1_score:	 0.72
Test f1_score:	 0.489 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.757
Test accuracy:	 0.616
Train precision: 0.77
Test precision:	 0.544
Train recall:	 0.757
Test recall:	 0.564
Train f1_score:	 0.76
Test f1_score:	 0.544 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 200}

Train accuracy:	 0.999
Test accuracy:	 0.69
Train precision: 0.999
Test precision:	 0.532
Train recall:	 0.99

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.981
Test accuracy:	 0.734
Train precision: 0.981
Test precision:	 0.578
Train recall:	 0.981
Test recall:	 0.568
Train f1_score:	 0.981
Test f1_score:	 0.571 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 40%|████      | 2/5 [03:41<05:19, 106.64s/it]

LogisticRegression: best params {}

Train accuracy:	 0.771
Test accuracy:	 0.532
Train precision: 0.766
Test precision:	 0.471
Train recall:	 0.771
Test recall:	 0.546
Train f1_score:	 0.767
Test f1_score:	 0.479 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.793
Test accuracy:	 0.601
Train precision: 0.798
Test precision:	 0.499
Train recall:	 0.793
Test recall:	 0.48
Train f1_score:	 0.795
Test f1_score:	 0.49 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.69
Train precision: 0.999
Test precision:	 0.54
Train recall:	 0.999
Test recall:	 0.546
Train f1_score:	 0.999
Test f1_score:	 0.543 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.734
Train precision: 0.999
Test precision:	 0.567
Train recall:	 0.999
Test recall:	 0.577
Train f1_score:	 0.999
Test f1_score:	 

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 60%|██████    | 3/5 [06:11<03:58, 119.41s/it]

LogisticRegression: best params {}

Train accuracy:	 0.848
Test accuracy:	 0.571
Train precision: 0.846
Test precision:	 0.497
Train recall:	 0.848
Test recall:	 0.485
Train f1_score:	 0.846
Test f1_score:	 0.487 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.772
Test accuracy:	 0.547
Train precision: 0.789
Test precision:	 0.483
Train recall:	 0.772
Test recall:	 0.43
Train f1_score:	 0.776
Test f1_score:	 0.445 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.685
Train precision: 0.999
Test precision:	 0.53
Train recall:	 0.999
Test recall:	 0.534
Train f1_score:	 0.999
Test f1_score:	 0.531 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.69
Train precision: 0.999
Test precision:	 0.532
Train recall:	 0.999
Test recall:	 0.543
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.985
Test accuracy:	 0.719
Train precision: 0.985
Test precision:	 0.563
Train recall:	 0.985
Test recall:	 0.559
Train f1_score:	 0.985
Test f1_score:	 0.559 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 80%|████████  | 4/5 [09:04<02:15, 135.63s/it]

LogisticRegression: best params {}

Train accuracy:	 0.898
Test accuracy:	 0.581
Train precision: 0.896
Test precision:	 0.524
Train recall:	 0.898
Test recall:	 0.572
Train f1_score:	 0.896
Test f1_score:	 0.534 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.74
Test accuracy:	 0.621
Train precision: 0.76
Test precision:	 0.568
Train recall:	 0.74
Test recall:	 0.501
Train f1_score:	 0.746
Test f1_score:	 0.524 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.685
Train precision: 0.999
Test precision:	 0.54
Train recall:	 0.999
Test recall:	 0.529
Train f1_score:	 0.999
Test f1_score:	 0.533 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.709
Train precision: 0.999
Test precision:	 0.55
Train recall:	 0.999
Test recall:	 0.541
Train f1_score:	 0.999
Test f1_score:	 0

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest: best params {'max_depth': 20, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.675
Train precision: 0.999
Test precision:	 0.536
Train recall:	 0.999
Test recall:	 0.505
Train f1_score:	 0.999
Test f1_score:	 0.515 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.987
Test accuracy:	 0.729
Train precision: 0.987
Test precision:	 0.563
Train recall:	 0.987
Test recall:	 0.577
Train f1_score:	 0.987
Test f1_score:	 0.57 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



100%|██████████| 5/5 [12:36<00:00, 151.20s/it]


 57%|█████▋    | 4/7 [53:31<39:59, 799.87s/it]


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.925
Test accuracy:	 0.567
Train precision: 0.923
Test precision:	 0.498
Train recall:	 0.925
Test recall:	 0.513
Train f1_score:	 0.924
Test f1_score:	 0.496 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.795
Test accuracy:	 0.537
Train precision: 0.802
Test precision:	 0.501
Train recall:	 0.795
Test recall:	 0.505
Train f1_score:	 0.796
Test f1_score:	 0.49 
 ------------------------------
XGboost: best params {'max_depth': 3, 'n_estimators': 200}

Train accuracy:	 0.999
Test accuracy:	 0.606
Train precision: 0.999
Test precision:	 0.496
Train recall:	 0.999
Test recall:	 0.487
Train f1_score:	 0.999
Test f1_score:	 0.491 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.645
Train precision: 0.999
Test precision:	 0.504
Train recall:	 0.999
Test recall:	 0.515
Train f1_score:	 0.999
Test f1_score

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 20%|██        | 1/5 [01:50<07:23, 110.90s/it]

SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.982
Test accuracy:	 0.719
Train precision: 0.982
Test precision:	 0.557
Train recall:	 0.982
Test recall:	 0.551
Train f1_score:	 0.982
Test f1_score:	 0.551 
 ------------------------------
LogisticRegression: best params {}

Train accuracy:	 0.722
Test accuracy:	 0.502
Train precision: 0.717
Test precision:	 0.489
Train recall:	 0.722
Test recall:	 0.524
Train f1_score:	 0.718
Test f1_score:	 0.47 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.758
Test accuracy:	 0.478
Train precision: 0.766
Test precision:	 0.456
Train recall:	 0.758
Test recall:	 0.465
Train f1_score:	 0.761
Test f1_score:	 0.444 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.64
Train precision: 0.999
Test precision:	 0.509
Train recall:	 0

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 40%|████      | 2/5 [04:12<06:00, 120.02s/it]

LogisticRegression: best params {}

Train accuracy:	 0.781
Test accuracy:	 0.537
Train precision: 0.776
Test precision:	 0.492
Train recall:	 0.781
Test recall:	 0.524
Train f1_score:	 0.777
Test f1_score:	 0.482 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.754
Test accuracy:	 0.571
Train precision: 0.764
Test precision:	 0.518
Train recall:	 0.754
Test recall:	 0.519
Train f1_score:	 0.756
Test f1_score:	 0.508 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.65
Train precision: 0.999
Test precision:	 0.561
Train recall:	 0.999
Test recall:	 0.528
Train f1_score:	 0.999
Test f1_score:	 0.541 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.714
Train precision: 0.999
Test precision:	 0.628
Train recall:	 0.999
Test recall:	 0.592
Train f1_score:	 0.999
Test f1_score

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 60%|██████    | 3/5 [07:02<04:30, 135.05s/it]

LogisticRegression: best params {}

Train accuracy:	 0.851
Test accuracy:	 0.552
Train precision: 0.848
Test precision:	 0.494
Train recall:	 0.851
Test recall:	 0.559
Train f1_score:	 0.848
Test f1_score:	 0.507 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.758
Test accuracy:	 0.567
Train precision: 0.763
Test precision:	 0.517
Train recall:	 0.758
Test recall:	 0.498
Train f1_score:	 0.759
Test f1_score:	 0.499 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.635
Train precision: 0.999
Test precision:	 0.504
Train recall:	 0.999
Test recall:	 0.503
Train f1_score:	 0.999
Test f1_score:	 0.503 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.724
Train precision: 0.999
Test precision:	 0.559
Train recall:	 0.999
Test recall:	 0.561
Train f1_score:	 0.999
Test f1_scor

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'rbf'}

Train accuracy:	 0.985
Test accuracy:	 0.749
Train precision: 0.985
Test precision:	 0.583
Train recall:	 0.985
Test recall:	 0.585
Train f1_score:	 0.985
Test f1_score:	 0.582 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 80%|████████  | 4/5 [10:20<02:34, 154.10s/it]

LogisticRegression: best params {}

Train accuracy:	 0.897
Test accuracy:	 0.606
Train precision: 0.895
Test precision:	 0.522
Train recall:	 0.897
Test recall:	 0.536
Train f1_score:	 0.896
Test f1_score:	 0.522 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.767
Test accuracy:	 0.562
Train precision: 0.781
Test precision:	 0.517
Train recall:	 0.767
Test recall:	 0.477
Train f1_score:	 0.771
Test f1_score:	 0.49 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.665
Train precision: 0.999
Test precision:	 0.571
Train recall:	 0.999
Test recall:	 0.55
Train f1_score:	 0.999
Test f1_score:	 0.555 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.739
Train precision: 0.999
Test precision:	 0.648
Train recall:	 0.999
Test recall:	 0.594
Train f1_score:	 0.999
Test f1_score

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.992
Test accuracy:	 0.739
Train precision: 0.992
Test precision:	 0.575
Train recall:	 0.992
Test recall:	 0.58
Train f1_score:	 0.992
Test f1_score:	 0.575 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



100%|██████████| 5/5 [14:22<00:00, 172.59s/it]


 71%|███████▏  | 5/7 [1:07:54<27:17, 818.80s/it]


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.917
Test accuracy:	 0.601
Train precision: 0.916
Test precision:	 0.535
Train recall:	 0.917
Test recall:	 0.579
Train f1_score:	 0.916
Test f1_score:	 0.541 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.777
Test accuracy:	 0.527
Train precision: 0.779
Test precision:	 0.469
Train recall:	 0.777
Test recall:	 0.435
Train f1_score:	 0.777
Test f1_score:	 0.45 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.586
Train precision: 0.999
Test precision:	 0.519
Train recall:	 0.999
Test recall:	 0.505
Train f1_score:	 0.999
Test f1_score:	 0.51 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.621
Train precision: 0.999
Test precision:	 0.489
Train recall:	 0.999
Test recall:	 0.49
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.981
Test accuracy:	 0.655
Train precision: 0.981
Test precision:	 0.506
Train recall:	 0.981
Test recall:	 0.507
Train f1_score:	 0.981
Test f1_score:	 0.504 
 ------------------------------
LogisticRegression: best params {}

Train accuracy:	 0.708
Test accuracy:	 0.522
Train precision: 0.701
Test precision:	 0.476
Train recall:	 0.708
Test recall:	 0.493
Train f1_score:	 0.701
Test f1_score:	 0.465 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 20%|██        | 1/5 [02:13<08:53, 133.26s/it]

[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.8
Test accuracy:	 0.512
Train precision: 0.806
Test precision:	 0.439
Train recall:	 0.8
Test recall:	 0.429
Train f1_score:	 0.801
Test f1_score:	 0.433 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 150}

Train accuracy:	 0.999
Test accuracy:	 0.621
Train precision: 0.999
Test precision:	 0.486
Train recall:	 0.999
Test recall:	 0.487
Train f1_score:	 0.999
Test f1_score:	 0.486 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.626
Train precision: 0.999
Test precision:	 0.492
Train recall:	 0.999
Test recall:	 0.465
Train f1_score:	 0.999
Test f1_score:	 0.474 
 ------------------------------
Random Forest: best params {'max_depth': 15, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.611
Train precision: 0.999
Test precision:	 0.47
Train recall:	 0.999
Test recall:	 0.438
Train f1_

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.983
Test accuracy:	 0.69
Train precision: 0.983
Test precision:	 0.525
Train recall:	 0.983
Test recall:	 0.535
Train f1_score:	 0.983
Test f1_score:	 0.527 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 40%|████      | 2/5 [04:46<06:57, 139.10s/it]

LogisticRegression: best params {}

Train accuracy:	 0.775
Test accuracy:	 0.537
Train precision: 0.77
Test precision:	 0.477
Train recall:	 0.775
Test recall:	 0.566
Train f1_score:	 0.772
Test f1_score:	 0.487 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.771
Test accuracy:	 0.611
Train precision: 0.774
Test precision:	 0.5
Train recall:	 0.771
Test recall:	 0.453
Train f1_score:	 0.772
Test f1_score:	 0.471 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.67
Train precision: 0.999
Test precision:	 0.571
Train recall:	 0.999
Test recall:	 0.53
Train f1_score:	 0.999
Test f1_score:	 0.545 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.695
Train precision: 0.999
Test precision:	 0.538
Train recall:	 0.999
Test recall:	 0.548
Train f1_score:	 0.999
Test f1_score:	 0

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.99
Test accuracy:	 0.685
Train precision: 0.99
Test precision:	 0.53
Train recall:	 0.99
Test recall:	 0.52
Train f1_score:	 0.99
Test f1_score:	 0.52 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 60%|██████    | 3/5 [07:32<04:54, 147.44s/it]

LogisticRegression: best params {}

Train accuracy:	 0.832
Test accuracy:	 0.557
Train precision: 0.828
Test precision:	 0.487
Train recall:	 0.832
Test recall:	 0.56
Train f1_score:	 0.828
Test f1_score:	 0.496 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.768
Test accuracy:	 0.517
Train precision: 0.774
Test precision:	 0.47
Train recall:	 0.768
Test recall:	 0.423
Train f1_score:	 0.769
Test f1_score:	 0.439 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.66
Train precision: 0.999
Test precision:	 0.505
Train recall:	 0.999
Test recall:	 0.507
Train f1_score:	 0.999
Test f1_score:	 0.506 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.685
Train precision: 0.999
Test precision:	 0.525
Train recall:	 0.999
Test recall:	 0.527
Train f1_score:	 0.999
Test f1_score:

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Random Forest: best params {'max_depth': 20, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.66
Train precision: 0.999
Test precision:	 0.508
Train recall:	 0.999
Test recall:	 0.493
Train f1_score:	 0.999
Test f1_score:	 0.497 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.992
Test accuracy:	 0.719
Train precision: 0.992
Test precision:	 0.559
Train recall:	 0.992
Test recall:	 0.559
Train f1_score:	 0.992
Test f1_score:	 0.555 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 80%|████████  | 4/5 [10:52<02:43, 163.17s/it]

LogisticRegression: best params {}

Train accuracy:	 0.887
Test accuracy:	 0.601
Train precision: 0.885
Test precision:	 0.525
Train recall:	 0.887
Test recall:	 0.57
Train f1_score:	 0.885
Test f1_score:	 0.537 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.762
Test accuracy:	 0.606
Train precision: 0.77
Test precision:	 0.527
Train recall:	 0.762
Test recall:	 0.487
Train f1_score:	 0.765
Test f1_score:	 0.5 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 400}

Train accuracy:	 0.999
Test accuracy:	 0.601
Train precision: 0.999
Test precision:	 0.479
Train recall:	 0.999
Test recall:	 0.474
Train f1_score:	 0.999
Test f1_score:	 0.476 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.675
Train precision: 0.999
Test precision:	 0.545
Train recall:	 0.999
Test recall:	 0.52
Train f1_score:	 0.999
Test f1_score:	 

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



100%|██████████| 5/5 [14:43<00:00, 176.60s/it]


 86%|████████▌ | 6/7 [1:22:37<13:58, 838.07s/it]


  0%|          | 0/5 [00:00<?, ?it/s]

LogisticRegression: best params {}

Train accuracy:	 0.906
Test accuracy:	 0.581
Train precision: 0.905
Test precision:	 0.525
Train recall:	 0.906
Test recall:	 0.578
Train f1_score:	 0.905
Test f1_score:	 0.532 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.768
Test accuracy:	 0.483
Train precision: 0.766
Test precision:	 0.441
Train recall:	 0.768
Test recall:	 0.415
Train f1_score:	 0.766
Test f1_score:	 0.414 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.562
Train precision: 0.999
Test precision:	 0.469
Train recall:	 0.999
Test recall:	 0.448
Train f1_score:	 0.999
Test f1_score:	 0.457 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.591
Train precision: 0.999
Test precision:	 0.486
Train recall:	 0.999
Test recall:	 0.445
Train f1_score:	 0.999
Test f1_scor

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 20%|██        | 1/5 [01:52<07:31, 112.90s/it]

LogisticRegression: best params {}

Train accuracy:	 0.702
Test accuracy:	 0.507
Train precision: 0.695
Test precision:	 0.466
Train recall:	 0.702
Test recall:	 0.544
Train f1_score:	 0.697
Test f1_score:	 0.469 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.732
Test accuracy:	 0.502
Train precision: 0.736
Test precision:	 0.449
Train recall:	 0.732
Test recall:	 0.447
Train f1_score:	 0.733
Test f1_score:	 0.427 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 300}

Train accuracy:	 0.999
Test accuracy:	 0.562
Train precision: 0.999
Test precision:	 0.474
Train recall:	 0.999
Test recall:	 0.458
Train f1_score:	 0.999
Test f1_score:	 0.465 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.581
Train precision: 0.999
Test precision:	 0.462
Train recall:	 0.999
Test recall:	 0.445
Train f1_score:	 0.999
Test f1_scor

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 40%|████      | 2/5 [04:14<06:04, 121.65s/it]

LogisticRegression: best params {}

Train accuracy:	 0.774
Test accuracy:	 0.542
Train precision: 0.769
Test precision:	 0.495
Train recall:	 0.774
Test recall:	 0.568
Train f1_score:	 0.77
Test f1_score:	 0.49 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.761
Test accuracy:	 0.552
Train precision: 0.772
Test precision:	 0.506
Train recall:	 0.761
Test recall:	 0.473
Train f1_score:	 0.765
Test f1_score:	 0.481 
 ------------------------------
XGboost: best params {'max_depth': 5, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.552
Train precision: 0.999
Test precision:	 0.421
Train recall:	 0.999
Test recall:	 0.408
Train f1_score:	 0.999
Test f1_score:	 0.413 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.606
Train precision: 0.999
Test precision:	 0.47
Train recall:	 0.999
Test recall:	 0.475
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.99
Test accuracy:	 0.69
Train precision: 0.99
Test precision:	 0.523
Train recall:	 0.99
Test recall:	 0.547
Train f1_score:	 0.99
Test f1_score:	 0.53 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 60%|██████    | 3/5 [06:59<04:29, 134.53s/it]

LogisticRegression: best params {}

Train accuracy:	 0.816
Test accuracy:	 0.542
Train precision: 0.811
Test precision:	 0.483
Train recall:	 0.816
Test recall:	 0.562
Train f1_score:	 0.813
Test f1_score:	 0.489 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 150}

Train accuracy:	 0.739
Test accuracy:	 0.502
Train precision: 0.741
Test precision:	 0.407
Train recall:	 0.739
Test recall:	 0.423
Train f1_score:	 0.738
Test f1_score:	 0.413 
 ------------------------------
XGboost: best params {'max_depth': 10, 'n_estimators': 500}

Train accuracy:	 0.999
Test accuracy:	 0.611
Train precision: 0.999
Test precision:	 0.5
Train recall:	 0.999
Test recall:	 0.491
Train f1_score:	 0.999
Test f1_score:	 0.495 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.65
Train precision: 0.999
Test precision:	 0.493
Train recall:	 0.999
Test recall:	 0.509
Train f1_score:	 0.999
Test f1_score:

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 80%|████████  | 4/5 [10:24<02:35, 155.58s/it]

LogisticRegression: best params {}

Train accuracy:	 0.873
Test accuracy:	 0.581
Train precision: 0.869
Test precision:	 0.514
Train recall:	 0.873
Test recall:	 0.546
Train f1_score:	 0.87
Test f1_score:	 0.515 
 ------------------------------
[518 315  42 137]
[414 414 414 414]
Adaboost: best params {'n_estimators': 200}

Train accuracy:	 0.742
Test accuracy:	 0.532
Train precision: 0.752
Test precision:	 0.471
Train recall:	 0.742
Test recall:	 0.449
Train f1_score:	 0.744
Test f1_score:	 0.45 
 ------------------------------
XGboost: best params {'max_depth': 6, 'n_estimators': 100}

Train accuracy:	 0.999
Test accuracy:	 0.581
Train precision: 0.999
Test precision:	 0.434
Train recall:	 0.999
Test recall:	 0.432
Train f1_score:	 0.999
Test f1_score:	 0.432 
 ------------------------------
Catboost: best params {}

Train accuracy:	 0.999
Test accuracy:	 0.66
Train precision: 0.999
Test precision:	 0.509
Train recall:	 0.999
Test recall:	 0.509
Train f1_score:	 0.999
Test f1_score:	

/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


SVM: best params {'decision_function_shape': 'ovo', 'gamma': 'scale', 'kernel': 'rbf'}

Train accuracy:	 0.995
Test accuracy:	 0.69
Train precision: 0.995
Test precision:	 0.531
Train recall:	 0.995
Test recall:	 0.529
Train f1_score:	 0.995
Test f1_score:	 0.525 
 ------------------------------


/trinity/home/a.shtanchaev/.conda/envs/newone/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



100%|██████████| 5/5 [14:28<00:00, 173.74s/it]


100%|██████████| 7/7 [1:37:06<00:00, 832.36s/it]

LogisticRegression: best params {}

Train accuracy:	 0.908
Test accuracy:	 0.611
Train precision: 0.906
Test precision:	 0.524
Train recall:	 0.908
Test recall:	 0.57
Train f1_score:	 0.907
Test f1_score:	 0.535 
 ------------------------------
